languageCode = "fr"
languageName = "French"
weight = 3
#title = ""

[params]
  displayName = "ğŸ‡«ğŸ‡· FranÃ§ais"
  isoCode = "fr"
  description = "IAM.FabioGrasso.net est un blog personnel de Fabio Grasso, Solutions Engineer chez Okta, axÃ© sur l'Identity & Access Management (IAM). "
  dateFormat = "2 January 2006"

[params.author]
  name = "Fabio Grasso"
  image = "img/profile-small.webp"
  headline = """
  <div id="headline">

  - ğŸ‘‹ Salut ! Je suis [**Fabio**](/about/), Solutions Engineer spÃ©cialisÃ© en ğŸ” Identity & Access Management (IAM). Je travaille entre la France ğŸ‡«ğŸ‡· et l'Italie ğŸ‡®ğŸ‡¹ pour [**Okta**](https://www.okta.com).
  - ğŸ“š Dans cet espace, je partage des idÃ©es, des expÃ©riences et des analyses sur le monde de l'identitÃ© numÃ©rique.
  - ğŸŒ Bien que ce site soit multilingue et que certains articles soient aussi disponibles en [Italien](/it) et en [FranÃ§ais](/fr), la plupart du contenu est en [Anglais](/en). Pour tout voir, choisissez [Anglais](/en) comme langue.
  
  </div>
  """
  bio = "Solutions Engineer spÃ©cialisÃ© dans l'Identity & Access Management (IAM) et la cybersÃ©curitÃ©."
  links = [
    # { link = "https://iam.fabiograsso.net" },
    { linkedin = "https://www.linkedin.com/in/fabiograsso82/"},
    { github = "https://github.com/fabiograsso/" },
    { instagram = "https://instagram.com/fabiograsso82"},
    { email = "mailto:iam@fabiograsso.net" },
    { rss = "/index.xml" },
    { ko-fi = "https://ko-fi.com/fabiograsso/tip" },
   ]