languageCode = "en"
languageName = "English"
weight = 1
#title = ""

[params]
  displayName = "ğŸ‡¬ğŸ‡§ English"
  isoCode = "en"
  description = "IAM.FabioGrasso.net is a personal blog by Fabio Grasso, a Solutions Engineer at Okta, focusing on Identity & Access Management (IAM)."
  dateFormat = "2 January 2006"

[params.author]
  name = "Fabio Grasso"
  image = "img/profile-small.webp"
  headline = """
  <div id="headline">

  - ğŸ‘‹ Ciao! Iâ€™m [**Fabio**](/about/), a *Solutions Engineer* specialized in ğŸ” *Identity & Access Management (IAM)*. I work between France ğŸ‡«ğŸ‡· and Italy ğŸ‡®ğŸ‡¹ for [**Okta**](https://www.okta.com).
  - ğŸ“š In this space, I share ideas, experiences, and insights about the world of digital identity.
  - ğŸŒ Although this site is multilingual and some posts are also in [Italian](/it) and [French](/fr), most content is in [English](/en). To see everything, pick [English](/en) as your language.
  
  </div>
  """
  bio = "Solutions Engineer specializing in Identity & Access Management (IAM) and cybersecurity."
  links = [
    # { link = "https://iam.fabiograsso.net" },
    { linkedin = "https://www.linkedin.com/in/fabiograsso82/"},
    { github = "https://github.com/fabiograsso/" },
    { instagram = "https://instagram.com/fabiograsso82"},
    { email = "mailto:iam@fabiograsso.net" },
    { rss = "/index.xml" },
    { ko-fi = "https://ko-fi.com/fabiograsso/tip" },
   ]
