languageCode = "it"
languageName = "Italian"
weight = 2
#title = "I AM Fabio"

[params]
  displayName = "ğŸ‡®ğŸ‡¹ Italiano"
  isoCode = "it"
  description = "IAM.FabioGrasso.net is a personal blog by Fabio Grasso, a Solutions Engineer at Okta, focusing on Identity & Access Management (IAM)."
  dateFormat = "2 January 2006"

[params.author]
  name = "Fabio Grasso"
  image = "img/profile-small.jpg"
  headline = """
  <div id="headline">

  - ğŸ‘‹ Ciao! Sono **[Fabio](/it/about/)**, Solutions Engineer specializzato in ğŸ” Identity & Access Management (IAM). Lavoro tra Francia ğŸ‡«ğŸ‡· e Italia ğŸ‡®ğŸ‡¹ per **[Okta](https://www.okta.com)**.
  - ğŸ“š In questo spazio, condivido idee, esperienze e approfondimenti sul mondo dell'identitÃ  digitale.
  - ğŸŒ Anche se questo sito Ã¨ multilingue e alcuni post sono disponibili anche in [Italiano](/it) e [Francese](/fr), la maggior parte dei contenuti Ã¨ in [Inglese](/en). Per visualizzare tutto, scegli [Inglese](/en) come lingua.
  
  </div>
  """
  bio = "A little bit about you"
   links = [
    # { link = "https://iam.fabiograsso.net" },
    { linkedin = "https://www.linkedin.com/in/fabiograsso82/"},
    { github = "https://github.com/fabiograsso/" },
    { instagram = "https://instagram.com/fabiograsso82"},
    { email = "mailto:iam@fabiograsso.net" },
    { rss = "/index.xml" },
    { ko-fi = "https://ko-fi.com/fabiograsso/tip" },
   ]
