
  en:
    weight: 1
    languageName: "ğŸ‡¬ğŸ‡§"
    languageCode: "en"
    weight: 1
    params:
      homeInfoParams:
        Title: "I AM Fabio"
        Content: >
           - ğŸ‘‹ Ciao! Iâ€™m **Fabio Grasso**, a *Solutions Engineer* specialized in ğŸ” *Identity & Access Management (IAM)*. I work between France ğŸ‡«ğŸ‡· and Italy ğŸ‡®ğŸ‡¹ for Okta.

           - ğŸš€ I love solving identity security challenges, helping companies implement agile, scalable, and effective Zero Trust strategies.

           - ğŸ“š In this space, I share ideas, experiences, and insights about the world of digital identity.
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 0
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 2
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 3
        - identifier: about
          name: About
          url: /about/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 10
#        - name: "@Author"
#          url: "https://reorx.com"
#          params:
#            external: true


  it:
    weight: 2
    languageName: "ğŸ‡®ğŸ‡¹"
    languageCode: "it"
    params:
      homeInfoParams:
        Title: "I AM Fabio"
        Content: >
          - ğŸ‘‹ Ciao! Sono **Fabio Grasso**, *Solutions Engineer* specializzato in ğŸ” *Identity & Access Management (IAM)*. Lavoro tra la Francia ğŸ‡«ğŸ‡· e lâ€™Italia ğŸ‡®ğŸ‡¹ per Okta 
          
          - ğŸš€ Amo risolvere le sfide legate alla sicurezza dellâ€™identitÃ , aiutando aziende a implementare strategie Zero Trust agili, scalabili ed efficaci.
          
          - ğŸ“š In questo spazio condivido idee, esperienze e visioni sul mondo dellâ€™identitÃ  digitale.
    weight: 2
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 0
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 2
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 3
        - identifier: about
          name: About
          url: /about/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 10
#        - name: "@Author"
#          url: "https://reorx.com"
#          params:
#            external: true


  fr:
    weight: 3
    languageName: "ğŸ‡«ğŸ‡·"
    languageCode: "fr"
    params:
      homeInfoParams:
        Title: "I AM Fabio"
        Content: >
          - ğŸ‘‹ Bonjourâ€¯! Je suis **Fabio Grasso**, *Solutions Engineer* spÃ©cialisÃ© en ğŸ” *Identity & Access Management (IAM)*. Je travaille entre la France ğŸ‡«ğŸ‡· et lâ€™Italie ğŸ‡®ğŸ‡¹ pour Okta.

          - ğŸš€ Jâ€™aime rÃ©soudre les dÃ©fis liÃ©s Ã  la sÃ©curitÃ© des identitÃ©s et aider les entreprises Ã  mettre en place des stratÃ©gies Zero Trust agiles, efficaces et faciles Ã  faire Ã©voluer.

          - ğŸ“š Ici, je partage des idÃ©es, des retours dâ€™expÃ©rience et des rÃ©flexions sur le monde de lâ€™identitÃ© numÃ©rique.
    weight: 3
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 0
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 2
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 3
        - identifier: about
          name: About
          url: /about/
          weight: 30
        - identifier: search
          name: Rechercher
          url: /search/
          weight: 10
#        - name: "@Author"
#          url: "https://reorx.com"
#          params:
#            external: true
